use std::{fs, process::Command};
#[test]
fn separate_processes_scan_query_plan_execute_restore() {
    let temp = tempfile::tempdir().unwrap();
    let root = fs::canonicalize(temp.path()).unwrap();
    let data = root.join("fixture");
    fs::create_dir_all(data.join("target/debug")).unwrap();
    fs::write(data.join("Cargo.toml"), "manifest").unwrap();
    let artifact = data.join("target/debug/a");
    fs::write(&artifact, "generated bytes").unwrap();
    let state = root.join("state");
    let run = |args: &[&str]| {
        let output = Command::new(env!("CARGO_BIN_EXE_stratum"))
            .arg("--data-dir")
            .arg(&state)
            .arg("--json")
            .args(args)
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{}",
            String::from_utf8_lossy(&output.stderr)
        );
        serde_json::from_slice::<serde_json::Value>(&output.stdout).unwrap()
    };
    let scan = run(&["scan", data.to_str().unwrap()]);
    assert_eq!(scan[0]["status"], "completed");
    assert!(
        !run(&["storage", "largest-files"])["items"]
            .as_array()
            .unwrap()
            .is_empty()
    );
    let plan = run(&["cleanup", "plan", "--path", artifact.to_str().unwrap()]);
    assert!(artifact.exists());
    let operation = run(&[
        "cleanup",
        "execute",
        plan["id"].as_str().unwrap(),
        "--approve",
        plan["approval_phrase"].as_str().unwrap(),
    ]);
    assert!(!artifact.exists());
    let restored = run(&["cleanup", "undo", operation["id"].as_str().unwrap()]);
    assert_eq!(restored["status"], "restored");
    assert_eq!(fs::read_to_string(artifact).unwrap(), "generated bytes");
}
