use std::{fs, process::Command};
#[test]
fn separate_processes_scan_query_plan_execute_restore() {
    let temp = tempfile::tempdir().unwrap();
    let root = fs::canonicalize(temp.path()).unwrap();
    let data = root.join("fixture");
    fs::create_dir_all(data.join("target/debug")).unwrap();
    fs::write(data.join("Cargo.toml"), "manifest").unwrap();
    let artifact = data.join("target/debug/a");
    fs::write(&artifact, "generated bytes").unwrap();
    let state = root.join("state");
    let run = |args: &[&str]| {
        let output = Command::new(env!("CARGO_BIN_EXE_stratum"))
            .arg("--data-dir")
            .arg(&state)
            .arg("--json")
            .args(args)
            .output()
            .unwrap();
        assert!(
            output.status.success(),
            "{}",
            String::from_utf8_lossy(&output.stderr)
        );
        serde_json::from_slice::<serde_json::Value>(&output.stdout).unwrap()
    };
    let scan = run(&["scan", data.to_str().unwrap()]);
    assert_eq!(scan[0]["status"], "completed");
    assert!(
        !run(&["storage", "largest-files"])["items"]
            .as_array()
            .unwrap()
            .is_empty()
    );
    let plan = run(&["cleanup", "plan", "--path", artifact.to_str().unwrap()]);
    assert!(artifact.exists());
    let operation = run(&[
        "cleanup",
        "execute",
        plan["id"].as_str().unwrap(),
        "--approve",
        plan["approval_phrase"].as_str().unwrap(),
    ]);
    assert!(!artifact.exists());
    let restored = run(&["cleanup", "undo", operation["id"].as_str().unwrap()]);
    assert_eq!(restored["status"], "restored");
    assert_eq!(fs::read_to_string(artifact).unwrap(), "generated bytes");
}
#[test]
fn separate_processes_quarantine_then_purge_with_its_own_phrase() {
    let temp = tempfile::tempdir().unwrap();
    let root = fs::canonicalize(temp.path()).unwrap();
    let data = root.join("fixture");
    fs::create_dir_all(data.join("target/debug")).unwrap();
    fs::write(data.join("Cargo.toml"), "manifest").unwrap();
    let artifact = data.join("target/debug/a");
    fs::write(&artifact, "generated bytes").unwrap();
    let state = root.join("state");
    let stratum = |args: &[&str]| {
        Command::new(env!("CARGO_BIN_EXE_stratum"))
            .arg("--data-dir")
            .arg(&state)
            .arg("--json")
            .args(args)
            .output()
            .unwrap()
    };
    let run = |args: &[&str]| {
        let output = stratum(args);
        assert!(
            output.status.success(),
            "{}",
            String::from_utf8_lossy(&output.stderr)
        );
        serde_json::from_slice::<serde_json::Value>(&output.stdout).unwrap()
    };
    run(&["scan", data.to_str().unwrap()]);
    let plan = run(&["cleanup", "plan", "--path", artifact.to_str().unwrap()]);
    let operation = run(&[
        "cleanup",
        "execute",
        plan["id"].as_str().unwrap(),
        "--approve",
        plan["approval_phrase"].as_str().unwrap(),
    ]);
    let id = operation["id"].as_str().unwrap();
    let held = operation["items"][0]["destination"]
        .as_str()
        .unwrap()
        .to_owned();
    let listed = run(&["cleanup", "operations"]);
    assert_eq!(listed[0]["id"], id);
    assert_eq!(listed[0]["in_quarantine"], 1);
    let phrase = listed[0]["purge_approval_phrase"]
        .as_str()
        .unwrap()
        .to_owned();
    assert_eq!(phrase, format!("PURGE {id}"));
    let refused = stratum(&[
        "cleanup",
        "purge",
        id,
        "--approve",
        plan["approval_phrase"].as_str().unwrap(),
    ]);
    assert!(!refused.status.success());
    let error: serde_json::Value = serde_json::from_slice(&refused.stdout).unwrap();
    assert_eq!(error["error"]["code"], "approval_required");
    assert!(std::path::Path::new(&held).is_file());
    let purged = run(&["cleanup", "purge", id, "--approve", &phrase]);
    assert_eq!(purged["status"], "purged");
    assert!(!std::path::Path::new(&held).exists());
    assert!(!artifact.exists());
    assert_eq!(run(&["cleanup", "operations"])[0]["in_quarantine"], 0);
}
